---

loglevel: DEBUG
database: dev.db
password: secret p@ss
owner_profile: http://example.com
cookie_secret_key: any value is fine in dev, even this literal string
blogs:
  - name: example
    type: built-in example
    uri: https://example.com/blog/
    slugprefix: /blog
  # - name: interpersonal-test
  #   type: github
  #   uri: https://interpersonal-test-blog.netlify.app/
  #   slugprefix: /blog
  #   github_owner: mrled
  #   github_repo: interpersonal-test-blog
  #   github_app_id: 1234567890
  #   github_app_private_key: |+
  #     -----BEGIN RSA PRIVATE KEY-----
  #     qwertyuiopasdfghjkl........ very long value here
  #     You can paste the entire thing here (just make sure its indented like this).
  #     Alternatively you can just set this value to a path to the key.
  #     -----END RSA PRIVATE KEY-----

