---

loglevel: DEBUG
database: dev.db
password: secret p@ss
owner_profile: http://example.com
cookie_secret_key: any value is fine in dev, even this literal string
blogs:
  - name: example
    type: built-in example
    uri: https://example.com/blog/
  # - name: interpersonal-test
  #   type: github
  #   uri: https://interpersonal-test-blog.netlify.app/
  #   github_owner: mrled
  #   github_repo: interpersonal-test-blog
  #   github_token: <your github personal token here>
