"""Tests for the root blueprint"""

from werkzeug.test import Client


def test_hello(client: Client):
    response = client.get("/hello")
    assert (
        response.data
        == b"Hello from Interpersonal, the connection between my little site and the indie web"
    )


def test_header(client: Client):
    response = client.get("/hello")
    assert (
        response.headers["Content-Security-Policy"]
        == "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'"
    )
    assert (
        response.headers["X-Interpersonal-Message"]
        == "Generated by Interpersonal, <https://github.com/mrled/interpersonal>"
    )
    assert (
        response.headers["Strict-Transport-Security"]
        == "max-age=31536000; includeSubDomains"
    )
